// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtDPGXQ5pi_aRg134WGmGvl1BESyoLlEU',
    appId: '1:930046274427:web:5705baf0fae2db568e6bde',
    messagingSenderId: '930046274427',
    projectId: 'flutter-firebase-project-30d83',
    authDomain: 'flutter-firebase-project-30d83.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-30d83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1qy4XCYNl6mZnHB7b800Jfc-NDvwm768',
    appId: '1:930046274427:android:01f7901af87d64ee8e6bde',
    messagingSenderId: '930046274427',
    projectId: 'flutter-firebase-project-30d83',
    storageBucket: 'flutter-firebase-project-30d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCFIaLOB9U17eusA6wc5bslyGT2P-pDhA',
    appId: '1:930046274427:ios:f0d08d4cacf323998e6bde',
    messagingSenderId: '930046274427',
    projectId: 'flutter-firebase-project-30d83',
    storageBucket: 'flutter-firebase-project-30d83.appspot.com',
    iosBundleId: 'com.example.sampleFirebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtDPGXQ5pi_aRg134WGmGvl1BESyoLlEU',
    appId: '1:930046274427:web:41279659a5b285698e6bde',
    messagingSenderId: '930046274427',
    projectId: 'flutter-firebase-project-30d83',
    authDomain: 'flutter-firebase-project-30d83.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-30d83.appspot.com',
  );
}
